### ISSUE TITLE
Mixed indentation styles in code

### ISSUE THREAD

**Issue by mateossh** [sdushantha/kunst#14]
While I was working on #13, I found out that there's still mixed indentation in this project... Even though I added EditorConfig in #4 a while ago :cry: 

Because world don't have any tool which lints bash scripts the way e.g ESLint does and developers doesn't pay enough attention to this, I think this repo should contain Pull Request template with little note "enforcing" them to check indents style or install editorconfig plugin to text editor of their choice.

**Comment by sdushantha** [comment]
I have had problems with indentation for a long time. I use Vim to write all of my code, but for some reason, the indentation is kinda messed up. So to fix that, I usally open my code in Sublime Text and fix the indentations. 

Do you know anyway how to fix this problem in Vim?

**Comment by mateossh** [comment]
I've never configured indentations in vim. I install [EditorConfig plugin](https://editorconfig.org/#download) to every text editor I use and let him do it for me. It just needs `.editorconfig` file in project's root directory.

If I were you, I would set indents I like the most in vim and install this plugin. A lot of projects uses this.

**Comment by sdushantha** [comment]
@mateossh Thank you, I will check it out :)

**Comment by granpino** [comment]
I am trying to use this with my Raspberry pi mp3 player. when I try ""sudo ./kunst --size 180x180px --music_dir ~/Music"" , I get ""error: file does not have an album art"" and ""./kunst: line 102: jq: command not found"". I know there is an Album art embedded with the file. Help Please.
