### ISSUE TITLE
Help needed with my project

### ISSUE THREAD

**Issue by granpino** [sdushantha/kunst#16]
I am trying to use this with my Raspberry pi mp3 player. when I try sudo `./kunst --size 180x180px --music_dir ~/Music` , I get `error: file does not have an album art` and `./kunst: line 102: jq: command not found`. I know there is an Album art embedded with the file. Help Please.

**Comment by sdushantha** [comment]
You must install ```jq```

https://stedolan.github.io/jq

**Comment by granpino** [comment]
This jq waaay over my head..

**Comment by sdushantha** [comment]
Just install ```jq``` with your package manager on your Raspberry Pi and everything should workfine after that.

**Comment by granpino** [comment]
OK. got it.
I installed Jq and sxiv and now it works. Now I just need to figure out how to save the image to the folder where my music is at so I can import it to the Player. My project is at https://github.com/granpino/Pi-Radio-mp3-

**Comment by sdushantha** [comment]
The album art is saved to `/tmp/kunst.jpg`
So just move the file to your folder.

**Comment by granpino** [comment]
I can not retrieve the image from the mp3 file but it downloads from the internet just fine.  https://www.hackster.io/Granpino/raspiplayer-internet-radio-and-mp3-player-rev2-3ddfdf

**Comment by granpino** [comment]
OK found the answer..I had to change the location of the Mp3 files. The MUSIC_DIR does not work.
       #ffmpeg -i "$MUSIC_DIR$(mpc current -f %file%)" $COVER -y &> /dev/null
        ffmpeg -i "/mnt/usbdrive/$(mpc current -f %file%)" $COVER -y &> /dev/nu$
