### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by sdushantha** [sdushantha/kunst#19]
@DragonGhost7 I just noticed that `kunst` is outputting an error:
![Screenshot_19-06-02_at_09-11-11](https://user-images.githubusercontent.com/27065646/58758086-83e35800-8516-11e9-9692-8bc21d0fcbf1.png)

I have no idea what line in the code is doing this. I think you might know because I am not getting this error in the older version of `kunst`.

Would be nice you could fix this. Dont rush, just take your time :)

**Comment by DragonGhost7** [comment]
I found what was causing the bug. When i call eyeD3 ot check are all the tags present, instead of using $MUSIC_DIR I use ~/Music , which causes confusion.
Also put these `" "` around it in case anyone has whitespaces in  the filename.

**Comment by DragonGhost7** [comment]
If you could please do check does it work on your machine.
Thanks!
