### ISSUE TITLE
Maybe remove tagging?

### ISSUE THREAD

**Issue by sdushantha** [sdushantha/kunst#21]
I am getting some strange errors
![Screenshot_19-06-02_at_13-59-28](https://user-images.githubusercontent.com/27065646/58760934-bdc85480-853e-11e9-9792-8dc8442cd11a.png)
And since there are many other programs which do auto tagging, I am thinking of removing the tagging feature because there is a risk already tagged files might get re-tagged.

It would be nicer to have `kunst` only deal with album art.
@DragonGhost7

**Comment by DragonGhost7** [comment]
Understood, should i remove the part that adds the cover art to the mp3 file if cant be extracted?

**Comment by DragonGhost7** [comment]
I still didnt remove `eyeD3` competely, it now only adds the cover image if `kunst` cant extract it.
Please tell me if you think it should be removed too.

**Comment by sdushantha** [comment]
Dont worry. I will just revert back to this commit beb2180

**Comment by DragonGhost7** [comment]
Ok, thanks. :)
Sorry for all te fuss.

**Comment by sdushantha** [comment]
@DragonGhost7 No worries :)
