### ISSUE TITLE
Support imv image viewer

### ISSUE THREAD

**Issue by Seirdy** [sdushantha/kunst#25]
[`imv`](https://github.com/eXeC64/imv) is another suckless/minimal image viewer, the main difference being that it works natively on Wayland as well as X11. It would be great if kunst could support `imv` and other custom image viewers.

**Comment by sdushantha** [comment]
@Seirdy That would be a great addition to kunst!
I am at the moment not able to test out `imv` because I dont have access to a Linux computer, so would it be possible for you to make a PR to support `imv`?

**Comment by Seirdy** [comment]
Busy atm due to school work; would be happy to do so Soon^TM.

**Comment by sdushantha** [comment]
@Seirdy Me too, exams are coming up... 👍

**Comment by sdushantha** [comment]
Closing this as it has been fixed in #29
