### ISSUE TITLE
Hangs at: kunst: swapped album art to

### ISSUE THREAD

**Issue by pjobson** [sdushantha/kunst#27]
Seems like it hangs, let me know what additional information you need and I'll provide it.

```
user@host:/media/Music/A/A Flock of Seagulls$ kunst --music_dir .
kunst: inspecting ..
error: file does not have an album art
error: cover not found online
kunst: swapped album art to
-----------------------------------------------------------------------------------------------------------------------------------------------------
^C
```

**Comment by cirrusUK** [comment]
`:/media/Music/A/A Flock of Seagulls$ kunst --music_dir .

is not correct syntax, try  kunst --music_dir=/your/path/to/mpd/music/"`
or  typing this in terminal before executing kunst 
'export KUNST_MUSIC_DIR="/your/path/to/mpd/music/"`
to make it permanant add it as environment  variable.
