### ISSUE TITLE
Does it work with flac files?

### ISSUE THREAD

**Issue by gregf** [sdushantha/kunst#3]
I only have flac files in my collection usually with just a cover.jpg file in the directory. I can see from the code it doesn't support this. So I used a program to embed the art into my flac files for a album and I'm still getting no art found errors.

```
error: file does not have an album art
kunst: swapped album art to Ghost - Life Eternal
```

**Comment by gregf** [comment]
Trying to debug this I found out I had a typo in my MUSIC_DIR path preventing it from working. Sorry for the noise.

**Comment by sdushantha** [comment]
No problem 😄
