### ISSUE TITLE
Images are low res if zoomed with sxiv

### ISSUE THREAD

**Issue by WovenTide** [sdushantha/kunst#35]
Hello !

It seems the pictures in Kunst have a fixed resolution. If my cover.jpg is 5000x5000 for exemple and if I try to zoom in wih sxiv when using Kunst the image is blurry and low res.
I've tried to change the size value with the "--size" option but it only widens the terminal around the picture.
Is there a way around this ? Is it possible to use a higher resolution by default for the images ?

Thank you for the help and thank you for making kunst !

**Comment by sdushantha** [comment]
Could you try adding this to your `.bashrc` or `.zshrc`? Or just run the command before executing `kunst`
```bash
export KUNST_SIZE="5000x5000"
```

**Comment by WovenTide** [comment]
I've added the line to my .zshrc but I get the same results as with the default size.
I've tried different values and even though kunst does say that the album art is resized, the resolution doesn't seem to improve.

Thanks for the help !

**Comment by sdushantha** [comment]
Hmm, strange.

Lets see if `ffmpeg` is actually able to get the 5000x5000 album cover. 
Run this command to extract the album cover from the audio file:
```bash
ffmpeg -loglevel error -i "path/to/music/file.mp3" "cover.jpg" -y
```
Then to check what the size of the album cover is, run the command below:
```bash
convert cover.jpg -print "Size: %wx%h\n" /dev/null
```

Let me know what the size is.

Also, if the above command does say that the image is 5000x5000, try opening it in `sxiv` and see if the image is clear when zoomed:

```bash
sxiv cover.jpg
```


---

If possble, could you send me the audio file so that I can test it?

**Comment by sdushantha** [comment]
@WovenTide

**Comment by WovenTide** [comment]
Hey, very sorry about the delay, it's been a busy week, I can answer way more quickly now.

It seems like I misunderstood some things about your program. I thought Kunst was looking for a .jpg inside the album directory, but re-reading the program description, it extracts the cover from the song ? So is it necessary to have an embedded cover inside the file ?

I've run the first command on some albums, but I always get this error : 
`Output file #0 does not contain any stream`

Does Kunst work properly with flac as well ? Unfortunately, I think my entire discography is in flac, so I didn't run the command on any mp3. But I can transcode some album if it's necessary.

Concerning the size of the album cover, the command says it's 4789x4764 (I was rounding up the number before). But I still have the problem with covers with normal sizes.

Yes the image is clear when zooming with sxiv on this specific cover.

Here's the specific file with its cover, but it's in flac and I don't think there's any embedded cover : https://send.firefox.com/download/8c990012b3bbc933/#-1kI7LbDBCgMI2-FyeEExA

Let me know if you need me to transcode an album or if you need anything else !

**Comment by sdushantha** [comment]
Hi @WovenTide, no worries about the delay, we all are a little busy especially with this corona virus going around.

> So is it necessary to have an embedded cover inside the file ?

No, because `kunst` is able to look for a .jpg in the album directory. #9 

What have you set `KUNST_MUSIC_DIR` to? Im guessing you might have forgotten to specify the music directory of the songs you are playing because when `kunst` looks for the album art, it look inside `KUNST_MUSIC_DIR`

**Comment by WovenTide** [comment]
Yes @sdushantha , I hope everything is fine for you !
`KUNST_MUSIC_DIR` is set to the directory which has my entire discography. I've tried to set it both with the command line and inside my .zshrc.
Do you have any other idea ?

**Comment by sdushantha** [comment]
@WovenTide 
I merged a few PRs that looked correct, without testing it because I did not have access to a Linux computer for a while. I just tested `kunst` and I am pretty sure that it is broken :(
I will have to fix this as soon as possible, but I gotta finish my school work first.

**Comment by sdushantha** [comment]
@WovenTide Could you please use [this version](https://github.com/sdushantha/kunst/blob/d0477c0fcb52761fdc3a1fd1e14dc8b89ba2b685/kunst) for now? It seems to be working without a problem.
Sorry for the inconvenience.

**Comment by sdushantha** [comment]
![kunst](https://user-images.githubusercontent.com/27065646/77579728-12c4c500-6edb-11ea-999f-58afe49edb4d.gif)
It works with the same setup that you have.

**Comment by WovenTide** [comment]
It's no problem ! Take your time !
As for the other version do I just have to replace what was in the original kunst file with the one you linked to me and rebuild it ? Sorry for the nooby question !

> It works with the same setup that you have.

Do you mean that it's possible to zoom in with the 1.2.5 version and have a clear resolution if the picture allows it ? Or that it shows the album cover ? The album cover is always shown, I just have an issue with zooming :)

I'll be able to answer you in a few hours !

**Comment by sdushantha** [comment]
@WovenTide 

> As for the other version do I just have to replace what was in the original kunst file with the one you linked to me and rebuild it ? Sorry for the nooby 

Dont be sorry, you learn by asking questions. Just follow the commands below:
```bash
# Clone the repo
$ git clone -n https://github.com/sdushantha/kunst

# Change your current directory to kunst
$ cd kunst

# Navigate to the branch with the hash d0477c0fcb52761fdc3a1fd1e14dc8b89ba2b685
$ git checkout d0477c0fcb52761fdc3a1fd1e14dc8b89ba2b685

# Install kunst
$ sudo make install
```
> Do you mean that it's possible to zoom in with the 1.2.5 version and have a clear resolution if the picture allows it ? Or that it shows the album cover ? The album cover is always shown, I just have an issue with zooming :)

Yup! Just make sure you do this:
```bash
export KUNST_SIZE="4000x4000"
```
![image](https://user-images.githubusercontent.com/27065646/77619312-4550db00-6f38-11ea-8d76-400e97ad4957.png)

**Comment by sdushantha** [comment]
@WovenTide Hello!
I have fixed the script now :)
Please try it and let me know if there are any problems.

**Comment by WovenTide** [comment]
Hey @sdushantha ! Hope you're fine ! :)
Sorry again for the late answer, i had some problems with the script, and tried to figure it out myself so you don't waste your time.
I went back to version 1.2.4 as you suggested, but the cover didn't change when the album was changing. So I tried to get back to version 1.2.5 but I couldn't find in the git manual a command which allows me to find the hash for 1.2.5. Thanks by the way for the thorough explanation, I didn't know the checkout argument (I don't know much about github).

As for the new version, 1.2.7, I'm getting this error when I try to launch it : 

`error: Could not find 'imagemagick', is it installed?
cat: /tmp/kunst.pid: No such file or directory
/usr/bin/kunst: line 169: kill:  &> /dev/null: arguments must be process or job IDs`

Imagemagick is indeed installed, I use version 7.2.10.2-2.
Do you want me to open a new issue ?

Thanks again for all the help ! :)

**Comment by sdushantha** [comment]
Hey @WovenTide,

> As for the new version, 1.2.7, I'm getting this error when I try to launch it:
`error: Could not find 'imagemagick', is it installed? cat: /tmp/kunst.pid: No such file or directory /usr/bin/kunst: line 169: kill: &> /dev/null: arguments must be process or job IDs`

I made some mistakes when I was trying to fix the script, but they all have been fixed now. I have tested everything and it seems to work with large album covers as well :)

---

>  couldn't find in the git manual a command which allows me to find the hash for 1.2.5

__Quick way to find the hash__:
1. Go to https://github.com/sdushantha/kunst/commits/master
2. Click on the commit you want the hash for. So, in your case you want the has for the version 1.2.5, so click on "**version bump 1.2.4 --> 1.2.5**"
3. Now, if you look under the big button that says **Browse files**, you will see some text that looks like this: `commit e03b872d27030261125bbab513ae2a069e640d5c`. The long text is the hash.

4. Copy that hash and then run `git checkout PASTE_HASH_HERE`


__Command line way to find the hash__:
1. After you have cloned the repo, and have moved into the `kunst` directory, run this command:
`git log`

2. Find the commit you want the hash for. So, in your case you want the has for the version 1.2.5, so using the arrow keys, scrooll down until you find the text "**version bump 1.2.4 --> 1.2.5**". Above that text, you will see hash:
![image](https://user-images.githubusercontent.com/27065646/77831505-de961200-712f-11ea-819f-09d81cd7692c.png)
3. Copy that hash and then run `git checkout PASTE_HASH_HERE`

---

Please try the newer version and let me know if things are working as expected :)

**Comment by WovenTide** [comment]
Thanks for all your time, the in depth explanation about the hash and for fixing the script ! :)
Everything works perfectly now.

I hope you have a nice day !

**Comment by sdushantha** [comment]
@WovenTide You too and remember to stay safe :)
