### ISSUE TITLE
imagemagick dependencies

### ISSUE THREAD

**Issue by ahloiscreamo** [sdushantha/kunst#39]
Hi ,
i think you should add imagemagick on the deps,
after adding all the necessary deps, the installation run fine but error when i try to run kunst.
`~
 kunst
error: Could not find 'convert', is it installed?
cat: /tmp/kunst.pid: No such file or directory
~`

So i install imagemagick which provide convert,
this happened on fresh install artix i3 system.
Thanks i enjoyed this app 🤘

![Screenshot from 2020-07-17 00-10-45](https://user-images.githubusercontent.com/9318372/87695503-26fe3c00-c7c2-11ea-9595-c23d9cc64c84.png)

**Comment by sdushantha** [comment]
Will fix that.

By the way, awesome setup! Looks really pretty 👍
