### ISSUE TITLE
Show in ncmpcpp

### ISSUE THREAD

**Issue by plasmoduck** [sdushantha/kunst#43]
Hi there, can you try to improve on this, so the album art can show in ncmpcpp split screen. Usually I have my ncmpcpp setup split so the left half shows me the tracks and the right half shows visualizer. Would be great if you can think of a way to show the album art in that visualizer screen instead.

Please see my screenshot as an example of the album art on ncmpcpp
![ncmpcpp](https://user-images.githubusercontent.com/38978656/91635394-9317c500-ea3b-11ea-90e9-c8e0f5ae0441.png)

**Comment by sdushantha** [comment]
@plasmoduck 
I dont plan on making `kunst` show album art on `ncmpcpp`, but it seems like someone has already managed to create what you are trying achieve: https://github.com/alnj/ncmpcpp-ueberzug

I have also seen many examples of people using `w3m-img` and `tmux` to show album art in a split pane. I have never tried this, but there are many screenshots on Google.
