### ISSUE TITLE
Support for mopidy

### ISSUE THREAD

**Issue by ahloiscreamo** [sdushantha/kunst#61]
Hello,

I recently switched to mopidy from mpd to use Spotify,
but it feels lonely without Kunst to complement the player, i use [bum](https://github.com/dylanaraps/bum) but it is slow in changing the covert art compared to kunst.

do you have any plan to support mopidy in the future?
Thanks.

**Comment by sdushantha** [comment]
Thank you for the feature request. I'd like to add support for mopidy but with the lack of time currently have, I unfortunately can't work on this. If you'd like to create a PR, feel free to do so :)

**Comment by ahloiscreamo** [comment]
Thanks for the fast reply, 
i see, that's very understandable, i'm just a casual linux user, i know ricing here and there but that's about it haha.
i will close this issue.
