### ISSUE TITLE
Support `cover.{jpg,png}`

### ISSUE THREAD

**Issue by rubdos** [sdushantha/kunst#9]
Many music organisers store their cover art along the album, instead of embedded inside the file. Typically, this file is called `cover.jpg`.

**Comment by sdushantha** [comment]
How would you want this to work?

```bash
kunst --image_file path/to/file.jpg
```

or 


```bash
kunst --image_file path/to/dir/
```

**Comment by gregf** [comment]
I would wan't it to look in each albums directory for a cover.jpg file. That's how my music is setup.

**Comment by rubdos** [comment]
Indeed what gregf writes. Just like

```
	ffmpeg -i "$MUSIC_DIR$(mpc current -f %file%)" $COVER -y &> /dev/null
```
looks in your `$MUSIC_DIR`, it should look for those cover files in the album dirs. Should be quite simple with `$MUSIC_DIR$(dirname `mpc current -f %file%`)/*.jpg` or something.

**Comment by sdushantha** [comment]
@rubdos 
I dont really have time at the moment to do it, but if you want to, you can submit a PR 😊
I have a lot of school work 📚
